function err = run_zeroing_routine(s826_obj, this_arm, arm_2_enc_lims)

    err = false;

    % Ask user to move arm 1 around for IX rising edges to zero encoders
    waitfor(msgbox( "Please zero the encoders for both arms. For the larger arm, move each joint to their CW and CCW extremes and then return them to a roughly central position. Press OK when complete.", ...
                    "Zeroing the Encoders", ...
                    'warn'));
    
    % Ask user to move arm 2 to a select config for setting predetermined
    % encoder values
    waitfor(msgbox( "For the second arm, move turntable fully CW, move the shoulder fully down until limit switch is triggered, and move the elbow fully up until hardstop. Press OK and HOLD POSITION UNTIL PROMPTED.", ...
                    "Zeroing the Encoders", ...
                    'warn'));
    
    % Set the counter to enc_zero_cts while user is holding arm in req pose
    for i = 1:length(this_arm.enc_ids)
        
        s826_obj.CounterPreloadWrite(   this_arm.board_num, ...
                                        this_arm.enc_ids(i), ...
                                        0, ...
                                        arm_2_enc_lims(i) );

        s826_obj.CounterPreload(    this_arm.board_num, ...
                                    this_arm.enc_ids(i), ...
                                    0, ...
                                    0  );

    end

    uiwait(msgbox("You can return the small arm to a neutral position", ...
                    "Zeroing the Arm", ...
                    'help'));

    user_confirmation = questdlg("Were you able to follow procedures and zero the arm?", ...
                                 "Zeroing the arm", ...
                                 "Yes", ...
                                 "No", ...
                                 "No");

    if user_confirmation == "No" || user_confirmation == ""
        err = true;
    end

end